# -*- coding: utf-8 -*-
"""backtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w89LGR3R6F-nH3wQawXw5_t5_IVCXFZu
"""

from xgboost import XGBRegressor
from src.walk_forward_splits import *
from src.models import har_forecast
import pandas as pd

def har_xgb_backtest(feature_df: pd.DataFrame, main_asset: str, selected_features: dict[str, list[str]],
                     train_ratio, best_params: dict, window: int) -> dict[str, pd.Series]:
    """
    Backtesting HAR-XGBoost model.

    This function creates HAR forecasts for main_asset and fits an XGB model to predict HAR
    residuals over different expanding window walk-forward splits. The forecasts are defined by
    the HAR baseline forecast, to which the predicted residuals are added.

    Parameters:
        feature_df
            DataFrame containing engineered features.
        main_asset
            Ticker of asset which is to be forecasted.
        selected_features
            Dictionary mapping asset identifiers to lists of selected feature names.
        train_ratio
            Fraction of observations used in initial training window.
        best_params
            Dictionary containing tuned XGBoost parameters.
        window
            Integer value representing rolling window length for HAR model.

    Returns:
        results
            Dictionary containing our true realized next-period target values, our
            HAR baseline forecasts, our HAR-XGBoost forecasts and the feature importances.
    """
    model_features = sum(selected_features.values(), [])
    vol_col = f"{main_asset}_d"

    y_pred_all, y_har_all, importances = [], [], []

    if len(feature_df) < max(window + 30, 80):
        raise ValueError("Not enough data for HAR.")

    #build model dataframe
    model_df = pd.concat([
        feature_df[vol_col].rename("vol"),
        feature_df[model_features]
    ], axis=1).dropna()

    splits = walk_forward_splits(model_df, train_ratio)

    for train_idx, test_idx in splits:
        train = model_df.iloc[train_idx].copy()
        test = model_df.iloc[test_idx].copy()

        #HAR computed using data up to test block
        combined_vol = model_df["vol"].iloc[:test_idx.stop]
        har_combined = har_forecast(combined_vol, window)

        train["har"] = har_combined.reindex(train.index)
        test["har"] = har_combined.reindex(test.index)

        y_train_resid = train["vol"].shift(-1) - train["har"]

        X_train = train[model_features]
        X_test = test[model_features]

        y_train_resid = y_train_resid.dropna()
        X_train = X_train.loc[y_train_resid.index]

        if len(X_train) == 0 or len(X_test) == 0:
            continue

        model = XGBRegressor(**best_params)
        model.fit(X_train, y_train_resid)

        imp = model.feature_importances_
        if imp.sum() > 0:
            imp = imp / imp.sum()
            importances.append(pd.Series(imp, index=X_train.columns))

        resid_pred = model.predict(X_test)
        final_pred = test["har"] + resid_pred

        y_pred_all.append(pd.Series(final_pred, index=test.index))
        y_har_all.append(test["har"])

    feat_imp = pd.concat(importances, axis=1).mean(axis=1).sort_values(ascending=False)

    y_pred = pd.concat(y_pred_all).sort_index()
    y_har = pd.concat(y_har_all).sort_index()

    target_series = feature_df[vol_col].shift(-1)

    mask = y_pred.notna() & target_series.notna()
    y_true = target_series.loc[mask]
    y_pred = y_pred.loc[mask]
    y_har = y_har.loc[y_pred.index]

    results = {
        "y_true": y_true,
        "y_pred": y_pred,
        "y_har": y_har,
        "feature_importance": feat_imp
    }

    return results