# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGdv1gNtfXNgYOHAiub-vl6JquLHoxhr
"""

import yfinance as yf
import pandas as pd
import numpy as np


#Loading data

def load_data(main_asset: str, cross_assets: list,
              start_date: str, end_date: str) -> tuple[pd.Series, pd.DataFrame, pd.Series]:
    """
    Load daily price data and compute returns for main and cross assets.

    Furthermore, the target is defined here. Data is imported from the yahoo finance
    'yfinance' library.

    Parameters:
        main_asset
            Ticker of main target asset to be forecasted.
        cross_assets
            Tickers of cross assets used as features.
        start_date
            Start date of data (format: YYYY/MM/DD).
        end_date
            End date of data (format: YYYY/MM/DD).

    Returns:
        price_df
            Series containing main asset prices.
        cross_prices
            Dataframe containing cross asset prices.
        target_5d
            Series containing log 5-day realized variance target.
    """

    #Main target prices
    price_df = yf.download(main_asset, start=start_date, end=end_date, auto_adjust=True, progress=False)["Close"]
    price_df = pd.Series(data = price_df[main_asset], index=price_df.index)

    #Compute log 5-day realized variance target
    epsilon = 1e-8
    returns = np.log(price_df / price_df.shift(1)).dropna()
    target_5d = np.log((returns**2).rolling(5).mean() + epsilon)

    if cross_assets:
        #Download cross-asset prices and align dates
        cross_prices = yf.download(cross_assets, start=start_date, end=end_date, auto_adjust=True, progress=False)["Close"]
        cross_prices = cross_prices.reindex(price_df.index).ffill()
    else:
        cross_prices = pd.DataFrame(index=price_df.index)

    return price_df, cross_prices, target_5d