# -*- coding: utf-8 -*-
"""features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Geq-gCsikMhB6K-YxzakKCGtBLqavgKM
"""

import pandas as pd
import numpy as np

#feature engineering section

def feature_engineering(target: pd.Series, main_asset: str, price_df: pd.DataFrame, cross_prices: pd.DataFrame) -> pd.DataFrame:
    """
    Create feature set for XGBoost residual modeling on top of HAR baseline.

    This function generates the feature set which includes HAR-like volatility components
    for the main asset, return and shock measures, downside and upside semivariance features,
    cross-asset return and spillover features.

    Parameters:
        target
            Target series used to build volatility-based predictors for our main_asset.
        main_asset
            Ticker of main asset which will be forecasted.
        price_df
            Series containing main asset prices.
        cross_prices
            Price dataframe of cross assets used to construct spillover features.

    Returns:
        feature_df
            DataFrame containing engineered features necessary for residual modeling.
    """
    returns = np.log(price_df / price_df.shift(1))
    feature_df = pd.DataFrame(index=target.index)

    #used for backtesting
    feature_df[f"{main_asset}_d"] = target

    #market-return features
    feature_df[f"{main_asset}_ret_5"] = returns.rolling(5).sum()

    feature_df[f"{main_asset}_abs_ret_1"] = returns.abs()
    feature_df[f"{main_asset}_abs_ret_5"] = returns.abs().rolling(5).mean()

    #leverage and asymmetry features
    feature_df[f"{main_asset}_neg_ret_1"] = (returns < 0).astype(int)
    feature_df[f"{main_asset}_neg_ret_sq_1"] = (returns < 0).astype(int) * (returns**2)
    feature_df[f"{main_asset}_downside_5"] = ((returns.clip(upper=0))**2).rolling(5).mean()
    feature_df[f"{main_asset}_upside_5"] = ((returns.clip(lower=0))**2).rolling(5).mean()

    #volatility dynamics
    feature_df[f"{main_asset}_vol_std_5"] = target.rolling(5).std()
    feature_df[f"{main_asset}_vol_std_22"] = target.rolling(22).std()

    #cross-asset spillovers
    for col in cross_prices.columns:
        r = np.log(cross_prices[col] / cross_prices[col].shift(1)) #cross asset return
        feature_df[f"{col}_ret_1"] = r
        feature_df[f"{col}_absret_5"] = r.abs().rolling(5).mean()

    feature_df = feature_df.replace([np.inf, -np.inf], np.nan)

    return feature_df


def target_feature_correlations(feature_df: pd.DataFrame, selected_features: dict[str, list[str]],
                                target_col: str = "har_resid", min_corr: float = 0.08) -> dict[str, list[str]]:
    """
    Here we filter the features based on a minimum correlation criterium.

    This function computes the correlation between the target and each candidate feature.
    If a feature exceeds 'min_corr', we filter the feature out. We subsequently display the
    correlation for each feature.

    Parameters:
        feature_df
            DataFrame containing engineered features and target.
        selected_features
            Dictionary mapping asset identifiers to lists of candidate feature names.
        target_col
            Name of target column.
        min_corr
            Minimum absolute correlation treshold.

    Returns:
        selected_features
            Dictionary containing selected features for each asset.
    """

    for asset, feats in selected_features.items():

        data = feature_df[feats + [target_col]].dropna()

        corr = data.corr(numeric_only=True)[target_col].drop(target_col)
        corr = corr[abs(corr) >= min_corr] #filter weakly correlated data

        out = pd.DataFrame({"corr": corr}).sort_values("corr", ascending=False)

        selected_features[asset] = list(out.index)

        print(f"{asset}")
        display(out)

    return selected_features