# -*- coding: utf-8 -*-
"""models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18W5lFeTzfGH58C5RBelGB40SXuP8bj0i
"""

from statsmodels.regression.rolling import RollingOLS
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor
from src.walk_forward_splits import *
import statsmodels.api as sm
import numpy as np
import pandas as pd
import optuna

#HAR Forecast
def har_forecast(vol_series: pd.Series, window: int) -> pd.Series:
    """
    Compute HAR-RV forecast using rolling OLS estimation.

    Here, the HAR model uses daily, weekly and monthly realized volatility components
    to forecast the volatility of the next period.

    Parameters:
        vol_series
            (Log) realized volatility series.
        window
            Rolling window size for estimating HAR coefficients.

    Returns:
        preds
            One-step ahead HAR predictions aligned with series index.
    """
    #HAR targets and features
    har_df = pd.DataFrame({
        'target': vol_series.shift(-1),
        'daily': vol_series,
        'weekly': vol_series.rolling(5).mean(),
        'monthly': vol_series.rolling(22).mean()
    }).dropna()

    X = sm.add_constant(har_df[['daily', 'weekly', 'monthly']])
    y = har_df['target']

    model = RollingOLS(y, X, window, min_nobs=52)
    results = model.fit()
    params_shifted = results.params.shift(1)

    #HAR model predictions
    preds = (
        params_shifted['const']
        + params_shifted['daily'] * har_df['daily']
        + params_shifted['weekly'] * har_df['weekly']
        + params_shifted['monthly'] * har_df['monthly']
    )

    preds = preds.dropna()
    return preds

def har_walk_forward_forecast(target_data: pd.Series, window: int, splits: list[tuple[slice, slice]]
                             ) -> tuple[pd.Series, pd.Series, pd.Series, pd.Series]:
    """
    Generate HAR walk-forward forecasts over a range of expanding-window splits

    In this implementation, we estimate our HAR model on data up to the end of the
    test block. Forecasts are obtained for our test set observations. Subsequently,
    we align the predicted values with the realized next-period target, compute residuals,
    and construct a naive benchmark based on the current-period target.

    Parameters:
        target_data
            Series used as forecasting target.
        window
            Rolling window length, used to determine HAR model coefficients.
        splits
            List containing walk-forward train and test split indices.

    Returns:
        y_true
            Next-period target values.
        y_pred
            HAR forecasts.
        y_naive
            Naive baseline forecast (based on current target value).
        residuals
            Errors in forecast defined by residuals = y_true - y_pred.
    """

    y_pred = pd.Series(index=target_data.index, dtype=float)

    #model for different splits
    for train_idx, test_idx in splits:

        combined = target_data.iloc[:test_idx.stop]
        preds = har_forecast(combined, window=window)

        idx = target_data.iloc[test_idx].index.intersection(preds.index)
        y_pred.loc[idx] = preds.loc[idx]

    target_series = target_data.shift(-1)

    #align indices
    valid_idx = y_pred.dropna().index.intersection(target_series.index)

    y_true = target_series.loc[valid_idx]
    y_pred = y_pred.loc[valid_idx]

    residuals = y_true - y_pred

    y_naive = target_data.loc[y_pred.index]

    return y_true, y_pred, y_naive, residuals

#Hyperparameter tuning
def xgb_tuning(feature_df: pd.DataFrame, selected_features: dict[str, list[str]],
                    train_ratio, train_cutoff: int, n_trials: int) -> dict:
    """
    Tune XGBoost parameters for residual prediction.

    This function uses the feature_df DataFrame up to a cutoff and tunes the
    XGBRegressor model on the HAR residual target using Optuna. The performance is
    evaluated using expanding-window walk-forward validation and RMSE as objective
    function.

    Parameters
        feature_df
            DataFrame containing features and HAR residual target.
        selected_features
            Dictionary mapping asset identifiers to lists of selected feature names.
        train_ratio
            Fraction of observations used in initial training window.
        train_cutoff
            Row cutoff splitting train set used for hyperparameter tuning.
        n_trials
            Number of Optuna trials for Bayesian hyperparameter search.

    Returns:
        opt_params
            Dictionary containing optimal parameters found by Optuna for XGBoost model.
    """

    #feature names
    model_features = sum(selected_features.values(), [])

    #use data up to cutoff
    df_sub = feature_df.iloc[:train_cutoff].copy()

    #use HAR residuals as target
    df_sub = df_sub[model_features + ["har_residual"]]
    df_sub = df_sub.dropna()

    X_train, y_train = df_sub[model_features], df_sub["har_residual"]

    #prevent data misalignment
    assert X_train.index.equals(y_train.index)

    def objective(trial):
        params = {
            "max_depth": trial.suggest_int("max_depth", 2, 6),
            "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.05, log=True),
            "n_estimators": trial.suggest_int("n_estimators", 200, 1000),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-4, 1.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True),
            "random_state": 42
        }

        splits = walk_forward_splits(X_train, train_ratio)
        scores = []

        #determine RMSE for splits
        for tr_idx, val_idx in splits:
            X_tr = X_train.iloc[tr_idx]
            y_tr = y_train.iloc[tr_idx]

            X_val = X_train.iloc[val_idx]
            y_val = y_train.iloc[val_idx]

            model = XGBRegressor(**params)
            model.fit(X_tr, y_tr)

            pred = model.predict(X_val)
            scores.append(np.sqrt(mean_squared_error(y_val, pred)))

        return np.mean(scores)

    sampler = optuna.samplers.TPESampler(seed=42)
    study = optuna.create_study(direction="minimize", sampler=sampler)
    study.optimize(objective, n_trials=n_trials)
    opt_params = study.best_params

    return opt_params