# -*- coding: utf-8 -*-
"""plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ep1HxbpT6YUPCY-MbRD6D19E1EeQBGo
"""

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

#This file contains functions for plots.

def plot_correlations(feature_df: pd.DataFrame, selected_features: dict[str, list[str]]) -> None:
    """
    Plot the correlation heatmap of selected features.
    This function takes feature names from feat_dict and computes the correlation matrix
    for these. These values are subsequently visualized on a heatmap.

    Parameters:
        feature_df
            DataFrame containing features and HAR residual target.
        selected_features
            Dictionary mapping asset identifiers to lists of selected feature names.

    Returns
        None
    """
    #feature names
    feat_cols = sum(selected_features.values(), [])

    #correlation matrix
    corr_matrix = feature_df[feat_cols].dropna().corr().loc[feat_cols, feat_cols]

    plt.figure(figsize=(4,3))
    sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", center=0, fmt=".2f", cbar=True)
    plt.title("Feature Correlations (AEX)")
    plt.show()

def plot_forecast_diagnostics(y_true: pd.Series, y_pred: pd.Series, residuals: pd.Series) -> None:
    """
    Plot forecast and residual diagnostics.
    This function generates a set of plots used for forecasting evaluation. We plot:
        - Observed vs. predicted values
        - Residual time series
        - Residual histogram distribution
        - Residual autocorrelation (ACF) and partial autocorrelation (PACF) functions

    Parameters
        y_true
            True target series.
        y_pred
            Predicted series obtained from forecasting model.
        residuals
            Forecasting residuals: residual = y_true - y_pred

    Returns
        None
    """

    #plot true vs predicted
    plt.figure(figsize=(14,4))
    plt.plot(y_true, label='True', alpha=0.8)
    plt.plot(y_pred, label='Predicted', alpha=0.8)
    plt.title(f"AEX Forecast True vs Predicted Log 5-Day Realized Variance")
    plt.xlabel("Date")
    plt.ylabel("Log Realized Variance")
    plt.grid()
    plt.legend()
    plt.show()

    #plot residuals
    plt.figure(figsize=(14,4))
    plt.plot(residuals)
    plt.title(f'AEX Forecast Residuals')
    plt.ylabel("Log Realized Variance")
    plt.xlabel("Date")
    plt.grid()
    plt.show()

    #residual histogram
    plt.figure(figsize=(14,4))
    sns.histplot(residuals, bins=30, kde=True)
    plt.title(f'AEX Forecast Residual Distribution. Average: {residuals.mean():.2f} +- {residuals.std():.2f}')
    plt.xlabel("Log Realized Variance")
    plt.ylabel("Count")
    plt.show()

    #plot acf and pacf
    fig, ax = plt.subplots(1, 2, figsize=(14,4))
    plot_acf(residuals.dropna(), lags=50, ax=ax[0])
    ax[0].set_title(f'AEX Forecast Residuals ACF')
    plot_pacf(residuals.dropna(), lags=50, ax=ax[1])
    ax[1].set_title(f'AEX Forecast Residuals PACF')
    plt.show()

def model_eval(results: dict[str, pd.Series]) -> None:
    """
    Plotting forecasts and residuals.
    This function plots our true values alongside the forecasts and residuals
    of our HAR baseline and HAR+XGB model. Furthermore, the residual distributions
    are compared and (partial) autocorrelation is visualized.

    Parameters
        results
            Dictionary containing y_true, y_pred, y_har and feature_imporance.

    Returns
        None
    """

    y_true = results["y_true"]
    y_pred = results["y_pred"]
    y_har = results["y_har"]

    residuals = y_true - y_pred
    residuals_har = y_true - y_har

    #Forecast plots
    plt.figure(figsize=(14,4))
    plt.plot(y_true, label="True", color='black')
    plt.plot(y_har, label="HAR", color='tab:blue')
    plt.plot(y_pred, label="HAR+XGB", color='tab:red')
    plt.title("Amsterdam AEX Volatility Forecast")
    plt.legend()
    plt.grid()
    plt.show()

    #Residuals plot
    plt.figure(figsize=(14,4))
    plt.plot(residuals, label='HAR+XGB residuals', color='tab:red')
    plt.plot(residuals_har, label='HAR residuals', color='tab:blue')
    plt.title(f"HAR + XGB Residuals")
    plt.legend()
    plt.grid()
    plt.show()

    #Residuals distribution
    plt.figure(figsize=(6,4))
    sns.histplot(residuals, bins=30, label='HAR+XGB', color='tab:red', kde=True)
    sns.histplot(residuals_har, bins=30, label='HAR', color='tab:blue', kde=True)
    plt.title(f"Residual Distribution \n HAR+XGB Residual = {residuals.mean():.2f} +- {residuals.std():.2f} \n HAR Residual = {residuals_har.mean():.2f} +- {residuals_har.std():.2f}")
    plt.legend()
    plt.show()

    #ACF and PACF plots
    fig, ax = plt.subplots(1,2, figsize=(12,4))
    plot_acf(residuals.dropna(), lags=40, ax=ax[0])
    plot_pacf(residuals.dropna(), lags=40, ax=ax[1])
    ax[0].set_title("Residual ACF")
    ax[1].set_title("Residual PACF")
    plt.show()

def feature_importance(results):
    """
    Plot XGB feature importance. Also prints importance aggregated by asset.

    Parameters
        results
            Dictionary containing model output. Has to contain feature importance.

    Returns
        None
    """

    feat_imp = results["feature_importance"]

    print(feat_imp)

    #per-asset importance
    asset_importance = {}

    for feat, val in feat_imp.items():
        asset = feat.split("_")[0]
        asset_importance[asset] = asset_importance.get(asset, 0) + val

    asset_importance = pd.Series(asset_importance).sort_values(ascending=False)

    #plotting
    plt.figure(figsize=(6,4))
    feat_imp.sort_values().plot(kind="barh", edgecolor='black')
    plt.title(f"XGB Feature Importance")
    plt.xlabel("Importance")
    plt.ylabel("Feature")
    plt.grid()
    plt.show()

    print(asset_importance)

def plot_targeting(vt_df: pd.DataFrame, target_vol: float) -> None:
    """
    Plot the volatility targeting results.
    This function plots the performance of our volatility-targeting
    strategies (HAR+XGB, HAR, and naive). It produces three subplots:

    - Cumulative performance (growth of 1 dollar)
    - Portfolio leverage over time
    - Forecasted annualized volatility with target volatility reference

    Parameters
        vt_df
            Dataframe of forecasts, leverage, returns, and cumulative performance.
        target_vol
            Target annualized volatility.

    Returns
        None
    """
    fig, axes = plt.subplots(3, 1, figsize=(12, 10), sharex=True)

    #Cumulative performance
    axes[0].plot(vt_df.index, vt_df["cum_xgb"], label="HAR+XGB", color='tab:red')
    axes[0].plot(vt_df.index, vt_df["cum_har"], label="HAR", color='tab:blue')
    axes[0].plot(vt_df.index, vt_df["cum_naive"], label="Naive", color='tab:green')
    axes[0].set_title("Cumulative Performance")
    axes[0].set_ylabel("Growth of 1 Dollar")
    axes[0].legend()
    axes[0].grid(True)

    #leverage
    axes[1].plot(vt_df.index, vt_df["lev_xgb"], label="HAR+XGB", color='tab:red')
    axes[1].plot(vt_df.index, vt_df["lev_har"], label="HAR", color='tab:blue')
    axes[1].plot(vt_df.index, vt_df["lev_naive"], label="Naive", color='tab:green')
    axes[1].axhline(1.0, linestyle="--")
    axes[1].set_title("Portfolio Leverage")
    axes[1].set_ylabel("Leverage")
    axes[1].legend()
    axes[1].grid(True)

    #Forecast annualized volatility
    axes[2].plot(vt_df.index, vt_df["pred_vol_ann_xgb"], label="HAR+XGB", color='tab:red')
    axes[2].plot(vt_df.index, vt_df["pred_vol_ann_har"], label="HAR", color='tab:blue')
    axes[2].plot(vt_df.index, vt_df["pred_vol_ann_naive"], label="Naive", color='tab:green')
    axes[2].axhline(target_vol, linestyle="--", label="Target Vol")
    axes[2].set_title("Forecast Annualized Variance")
    axes[2].set_ylabel("Log Realized Variance")
    axes[2].set_xlabel("Date")
    axes[2].legend()
    axes[2].grid(True)

    plt.tight_layout()
    plt.show()