# -*- coding: utf-8 -*-
"""strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDJE32dE-viit_lQkBKiYALDUpzTWeBZ
"""

import pandas as pd
import numpy as np

#This file contains our volatility targeting strategy.

def targeting_stats(ret: pd.Series, annualization: int) -> tuple[float, float, float, float, pd.Series]:
    """
    This function takes as input the returns and puts out some statistics including
    sharpe and max drawdown.

    Parameters:
        ret
            Returns Series.
        annualization
            Annualization factor.

    Returns:
        ann_ret
            Annual return.
        ann_vol
            Annual volume.
        sharpe
            Sharpe ratio.
        cum
            cumulative returns.
    """
    ann_ret = ret.mean() * annualization
    ann_vol = ret.std() * np.sqrt(annualization)
    sharpe = ann_ret / ann_vol

    cum = np.exp(ret.cumsum())
    peak = cum.cummax()
    drawdown = cum / peak - 1.0
    max_dd = drawdown.min()

    return ann_ret, ann_vol, sharpe, max_dd, cum

def vol_targeting(results: dict, price_df: pd.Series, target_vol: float,
                  min_lev: float, max_lev: float, tcost_per_turnover: float,
                  annualization: int) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Volatility-targeting algorithm for XGB, HAR, and naive forecasts.

    Assumption:
        results["y_pred"], results["y_har"], and results["y_true"] are aligned by forecast date.
        A forecast dated t is used to set leverage for the next return, so leverage is shifted by 1.

    Parameters
        results
            Dictionary containing forecast series, y_pred, y_har, y_true.
        price_df
            Price series per date.
        target_vol
            Target annualized volatility.
        min_lev
            Minimum leverage floor.
        max_lev
            Maximum leverage cap.
        tcost_per_turnover
            Transaction cost per leverage turnover.
        annualization
            Trading days per year.

    Returns
        vt_df
            Dataframe of forecasts, leverage, returns, and cumulative performance.
        summary_df
            Strategy summary table.
    """

    asset_ret = np.log(price_df / price_df.shift(1)).rename("asset_ret")

    #predicted values
    vt_df = pd.DataFrame(index=results["y_pred"].index)
    vt_df["pred_log_var_xgb"] = results["y_pred"]
    vt_df["pred_log_var_har"] = results["y_har"]
    vt_df["pred_log_var_naive"] = results["y_true"].shift(1)
    vt_df["asset_ret"] = asset_ret.reindex(vt_df.index)

    forecast_names = ["xgb", "har", "naive"]

    #convert log-variance forecasts to annualized volatility forecasts
    for name in forecast_names:
        vt_df[f"pred_vol_ann_{name}"] = np.exp(vt_df[f"pred_log_var_{name}"] / 2) * np.sqrt(annualization)

    # build vol-targeted returns
    for name in forecast_names:
        pred_vol = vt_df[f"pred_vol_ann_{name}"]

        lev = (target_vol / pred_vol).clip(lower = min_lev, upper = max_lev)

        vt_df[f"lev_{name}"] = lev
        vt_df[f"ret_{name}_gross"] = lev.shift(1) * vt_df["asset_ret"]
        vt_df[f"turnover_{name}"] = lev.diff().abs()
        vt_df[f"ret_{name}_net"] = vt_df[f"ret_{name}_gross"] - tcost_per_turnover * vt_df[f"turnover_{name}"]

    vt_df = vt_df.dropna(subset=["ret_xgb_net", "ret_har_net", "ret_naive_net"])

    #buy&hold
    vt_df["ret_bh_net"] = vt_df["asset_ret"]
    vt_df["cum_bh"] = np.exp(vt_df["ret_bh_net"].cumsum())

    rows = []
    labels = {"xgb": "HAR+XGB Vol Targeted", "har": "HAR Vol Targeted", "naive": "Naive Vol Targeted"}

    #generate statistics
    for name in forecast_names:
        ann_ret, ann_vol, sharpe, max_dd, cum = targeting_stats(vt_df[f"ret_{name}_net"], annualization)

        vt_df[f"cum_{name}"] = cum

        rows.append({
            "Strategy": labels[name],
            "Annual Return": ann_ret,
            "Annual Vol": ann_vol,
            "Sharpe": sharpe,
            "Max Drawdown": max_dd,
            "Average Leverage": vt_df[f"lev_{name}"].mean(),
            "Average Turnover": vt_df[f"turnover_{name}"].mean()})

    #buy-and-hold statistics
    ann_ret, ann_vol, sharpe, max_dd, cum = targeting_stats(vt_df["ret_bh_net"], annualization)
    rows.append({
        "Strategy": "Buy & Hold",
        "Annual Return": ann_ret,
        "Annual Vol": ann_vol,
        "Sharpe": sharpe,
        "Max Drawdown": max_dd,
        "Average Leverage": 1.0,
        "Average Turnover": 0.0})

    summary_df = pd.DataFrame(rows)

    return vt_df, summary_df