# -*- coding: utf-8 -*-
"""Walk_forward_splits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D41iohOTHGu-Ckh7T8F3Yokj7nvFE8dQ
"""

import pandas as pd

#Walk forward splits

def walk_forward_splits(df: pd.DataFrame, train_ratio: float, test_block_size: int = 42)-> list[tuple[slice, slice]]:
    """
    Create expanding-window walk-forward splits for time series.

    Here, the training set starts with a fraction of the dataset and expands
    with each iteration. The test set consists of fixed-size blocks moving forward
    as we progress.

    Parameters
        df
            Dataframe which will be split.
        train_ratio
            Fraction of observations used in initial training window.
        test_block_size
            Number of observations for each test block.

    Returns
        splits
            List containing (train_idx, test_idx) pairs which represent our
            train and test slices for each walk-forward iteration.
    """
    n = len(df)
    train_size = int(train_ratio * n)
    splits = []
    start = train_size
    while start + test_block_size <= n:
        train_idx = slice(0, start)
        test_idx = slice(start, start + test_block_size)
        splits.append((train_idx, test_idx))
        start += test_block_size

    return splits